feat:create helpful page
smerch88/techgen-front pull request #29
Opened 2023-02-07 09:10 UTC by Maryna-Bazylevska

2023-02-07 10:58 UTC, truescoutjohn requested changes

2023-02-07 10:58 UTC, truescoutjohn commented on src/pages/Helpful/helpful.styled.js
> +  float: 'right',
try to use flex-box instead of float

2023-02-07 10:58 UTC, truescoutjohn commented on src/pages/Helpful/Helpful.jsx
> +import getHelpfuls from './api';
You should use the gateway folder for API

2023-02-07 10:58 UTC, truescoutjohn commented on src/pages/Helpful/Helpful.jsx
> +import Sidebar from '../../components/Sidebar/Sidebar';
We have configured the path of Sidebar and you can use path like 'components/Sidebar/Sidebar' instead of '../../components/Sidebar/Sidebar'

2023-02-07 10:58 UTC, truescoutjohn commented on src/pages/Helpful/Helpful.jsx
> +  const [helpfuls, setHelpfuls] = useState([]);
Better to call this variable like articles or services instead of helpful

2023-02-07 11:42 UTC, Maryna-Bazylevska commented on src/pages/Helpful/helpful.styled.js
> +  float: 'right',
done

2023-02-07 11:42 UTC, Maryna-Bazylevska commented on src/pages/Helpful/Helpful.jsx
> +import getHelpfuls from './api';
done

2023-02-07 11:42 UTC, Maryna-Bazylevska commented on src/pages/Helpful/Helpful.jsx
> +import Sidebar from '../../components/Sidebar/Sidebar';
done

2023-02-07 11:42 UTC, Maryna-Bazylevska commented on src/pages/Helpful/Helpful.jsx
> +  const [helpfuls, setHelpfuls] = useState([]);
done

2023-02-07 22:14 UTC, smerch88 approved these changes

2023-02-07 22:15 UTC, smerch88 approved these changes

2023-02-08 07:02 UTC, truescoutjohn approved these changes

2023-02-08 09:43 UTC, merged